id: alteryx_one_deployment_percentage
name: Alteryx One Deployment Percentage
description: Percentage of total customer accounts that have deployed Alteryx One.
product: alteryx_one
status: validated
category: deployment
definition:
  business: Percentage of total customer accounts that have deployed Alteryx One.
  technical: From ALTERYX_ONE_DEPLOYED_ACCOUNT_PERCENTAGE_VIEW
source:
  database: DISCOVERY_PRODUCT_MANAGEMENT
  schema: METRIC_STORE
  base_tables: []
sql_template: "SELECT YEAR_MONTH ,\n    ((COUNT(DISTINCT CASE WHEN PRICING_AND_PACKAGING='2025'\
  \ THEN BILLING_ACCOUNT_ID end)/\n      COUNT(DISTINCT BILLING_ACCOUNT_ID)))  as\
  \ \"PERCENTAGE_AYX_ONE_ACCOUNTS\"\n    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.ALTERYX_MONTHLY_ACCOUNT_ONBOARDING_ADAPTION_USAGE_AT\n\
  \    WHERE \n    LICENSE_TYPE = 'Purchase' \n    AND YEAR_MONTH > DATEADD('YEAR',\
  \ -1, YEAR_MONTH)  \n    GROUP BY YEAR_MONTH  \n    ORDER BY YEAR_MONTH DESC;"
queries: []
aggregation_level: overall
grain: overall
freshness: daily
filters: []
depends_on: []
related_metrics: []
maintainer: analytics@alteryx.com
tags:
- deployment
- alteryx-one
last_updated: '2026-08-03'
version: '1.0'
